### ISSUE TITLE
getting error via composer installation

### ISSUE THREAD

**Issue by truelineinfotech** [samsonasik/ci4-album#1]
i am getting error via composer installation
![image](https://user-images.githubusercontent.com/3807730/76384163-2f61e880-6384-11ea-9c01-a3a97820e517.png)

**Comment by samsonasik** [comment]
That's a git clone(manually), plese re-read the readme, that's not via composer. For composer, you can just run: 

```bash
composer require samsonasik/ci4-album
```

For git clone, please read this https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey 

or you can clone from https version: 

```
git clone https://github.com/samsonasik/ci4-album.git
```

Please check the "Clone or Download" button.

**Comment by truelineinfotech** [comment]
thanks for quick reply.
